config/routes.rb
Rails.application.routes.draw do

  
  get 'worship_slide_op/create'
  
  get 'worship_slide_op/destroy_data'
  
  get 'worship_slide_op/download'
  
  
  
  resources :worship_slides
  resources :songs
  get 'download_song' => 'songs#download'
  get 'delete_song', to: 'songs#delete_data'
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'pages#home'
  resources :filemakers
  resources :slidevers
 
  resources :users
  post '/signup',  to: 'users#create'
  get  '/signup',  to: 'users#new'
  
  get '/', to: 'pages#home'
  get  'help',    :to => 'pages#help'
  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  
  get "download_file", to: "slidevers#download_file"
  get 'delete_data', to: 'slidevers#delete_data'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  

end

app/models/song.rb
class Song < ApplicationRecord
   validates_uniqueness_of :name
   
   has_one :song1 ,  :class_name => 'Song', :foreign_key => 'song1'
   has_one :song2 ,  :class_name => 'Song', :foreign_key => 'song2'
   has_one :song3 ,  :class_name => 'Song', :foreign_key => 'song3'
   has_one :song4 ,  :class_name => 'Song', :foreign_key => 'song4'
   has_one :song5 ,  :class_name => 'Song', :foreign_key => 'song5'
   has_one :song6 ,  :class_name => 'Song', :foreign_key => 'song6'
   has_one :song7 ,  :class_name => 'Song', :foreign_key => 'song6'
   has_one :hymn1 ,  :class_name => 'Song', :foreign_key => 'hymn1'
   has_one :hymn2 ,  :class_name => 'Song', :foreign_key => 'hymn2'
   has_one :hymn3 ,  :class_name => 'Song', :foreign_key => 'hymn3'
   has_one :hymn4 ,  :class_name => 'Song', :foreign_key => 'hymn3'
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy, :upload, :download, :delete_data]
  before_action :song_name_hymn, only: [:create, :update]
  # GET /songs
  # GET /songs.json
  def index
    @songs = Song.all.order(date: :desc)
  end

  # GET /songs/1
  # GET /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
    @song.date = Date.today
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs
  # POST /songs.json
  def create
    
    upload
    
    @song = Song.new(song_params)
    
    
    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: 'Song was successfully created.' }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1
  # PATCH/PUT /songs/1.json
  def update
    upload
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: 'Song was successfully updated.' }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1
  # DELETE /songs/1.json
  def destroy
    @song.destroy
    respond_to do |format|
      format.html { redirect_to songs_url, notice: 'Song was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  
  def upload
   uploaded_io = params[:song][:data]
   if uploaded_io != nil
      params[:song][:data] = uploaded_io.read
   end
#    File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'wb') do |file|
#     file.write(uploaded_io.read)
#    end
  end
  
  def download
    
    if @song.data == nil 
        redirect_back(fallback_location: root_path)
       # send_file path+filename, :type => 'application/pptx', :disposition => 'attachment'
    else
        send_data @song.data, filename: @song.name + ".pptx",type: 'application/pptx', disposition: 'attachment'
    end
      
  end
  
  def delete_data
    @song.data=nil
    @song.save
    respond_to do |format|
      format.html { redirect_to @song, notice: 'File data was successfully destroyed.' }
      format.json { render :show, status: :ok, location: @song }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end
    
    # Never trust parameters from the scary internet, only allow the white list through.
    def song_params
      params.require(:song).permit(:date, :name, :typehymn, :data)
    end
    
    # Song name change for hymns
    def song_name_hymn
      
      if params[:song][:typehymn] == "1" then
        params[:song][:name] = "[Гимн] " + params[:song][:name].to_s
      else
        params[:song][:name] =  params[:song][:name].gsub("[Гимн] ","")
       
      end
     
    end
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/songs/_form.html.erb
<%= form_for(song) do |f| %>
  <% if song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% song.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :Hymn%>
    <%= f.check_box :typehymn %>
  </div>
  
  <div class="field">
    <%= f.label :file %>
    <%=  f.file_field :data %>
  

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>|

app/views/songs/index.html.erb
<% if not logged_in? %>  
<%= controller.redirect_to root_url %>
<% end %>
<% provide(:title, 'Songs') %>
<h1>Songs</h1>
<%= link_to 'New Song', new_song_path , class: "btn btn-primary" %>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Name</th>
      <th>Hymn</tWh>
      <th>Data</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.date %></td>
        <td><%= song.name %></td>
        <td><%=check_box_tag 'song[typehymn]', 1, song.typehymn %></td>
        <td> <% if song.data == nil %>
                <%= "Need to upload" %>
              <% else %>
                <%= "Exists" %>
              <% end %></td>
        <td><%= link_to 'Show', song , class: "btn btn-info" %></td>
        <td><%= link_to 'Edit', edit_song_path(song) , class: "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path %>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @song.date %>
</p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Hymn:</strong>
  <%= @song.typehymn %>
</p>

<p>
  <strong>Data:</strong>
   <% if @song.data == nil %>
          <%= @song.data %>
    <% else %>
        <%= "exists" %>
    <% end %>

</p>


<%= link_to 'Edit', edit_song_path(@song) %> | 
<%= link_to 'Back', songs_path %> | 
<%= link_to 'Download', download_song_path(:id => @song) , target: 'self' %> |
<%= link_to 'Delete data', delete_song_path(:id => @song) %>  
<%= link_to 'New Song', new_song_path %>