config/routes.rb
Rails.application.routes.draw do

  
  get 'worship_slide_op/create'
  
  get 'worship_slide_op/destroy_data'
  
  get 'worship_slide_op/download'
  
  
  
  resources :worship_slides
  resources :songs
  get 'download_song' => 'songs#download'
  get 'delete_song', to: 'songs#delete_data'
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'pages#home'
  resources :filemakers
  resources :slidevers
 
  resources :users
  post '/signup',  to: 'users#create'
  get  '/signup',  to: 'users#new'
  
  get '/', to: 'pages#home'
  get  'help',    :to => 'pages#help'
  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  
  get "download_file", to: "slidevers#download_file"
  get 'delete_data', to: 'slidevers#delete_data'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  

end

app/models/worship_slide.rb
class WorshipSlide < ApplicationRecord
    belongs_to :song1, :class_name => "Song"
    belongs_to :song2, :class_name => "Song"
    belongs_to :song3, :class_name => "Song"
    belongs_to :song4, :class_name => "Song"
    belongs_to :song5, :class_name => "Song"
    belongs_to :song6, :class_name => "Song"
    belongs_to :song7, :class_name => "Song"
    belongs_to :hymn1, :class_name => "Song"
    belongs_to :hymn2, :class_name => "Song"
    belongs_to :hymn3, :class_name => "Song"
    belongs_to :hymn4, :class_name => "Song"
    belongs_to :verse, :class_name => "Slidever"
end

app/controllers/worship_slides_controller.rb
class WorshipSlidesController < ApplicationController
  before_action :set_worship_slide, only: [:show, :edit, :update, :destroy]

  # GET /worship_slides
  # GET /worship_slides.json
  def index
    @worship_slides = WorshipSlide.order(date: :desc).paginate(page: params[:page], per_page: 10)
  end

  # GET /worship_slides/1
  # GET /worship_slides/1.json
  def show
  end

  # GET /worship_slides/new
  def new
    @worship_slide = WorshipSlide.new
    @worship_slide.date = Date.today
  end

  # GET /worship_slides/1/edit
  def edit
  end

  # POST /worship_slides
  # POST /worship_slides.json
  def create
    @worship_slide = WorshipSlide.new(worship_slide_params)

    respond_to do |format|
      if @worship_slide.save
        format.html { redirect_to @worship_slide, notice: 'Worship slide was successfully created.' }
        format.json { render :show, status: :created, location: @worship_slide }
      else
        format.html { render :new }
        format.json { render json: @worship_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /worship_slides/1
  # PATCH/PUT /worship_slides/1.json
  def update
    @worship_slide.data = nil
    respond_to do |format|
      if @worship_slide.update(worship_slide_params)
        format.html { redirect_to @worship_slide, notice: 'Worship slide was successfully updated.' }
        format.json { render :show, status: :ok, location: @worship_slide }
      else
        format.html { render :edit }
        format.json { render json: @worship_slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /worship_slides/1
  # DELETE /worship_slides/1.json
  def destroy
    @worship_slide.destroy
    respond_to do |format|
      format.html { redirect_to worship_slides_url, notice: 'Worship slide was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_worship_slide
      @worship_slide = WorshipSlide.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def worship_slide_params
      params.require(:worship_slide).permit(:date, :song1_id, :song2_id, :song3_id, :song4_id, :song5_id, :song6_id, :song7_id, :hymn1_id, :verse_id, :hymn2_id, :hymn3_id, :hymn4_id)
    end
end

app/helpers/worship_slides_helper.rb
module WorshipSlidesHelper
end

app/views/worship_slides/_form.html.erb
<%= form_for(worship_slide) do |f| %>
  <% if worship_slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(worship_slide.errors.count, "error") %> prohibited this worship_slide from being saved:</h2>

      <ul>
      <% worship_slide.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %>
    <%= f.date_field :date %>
  </div>

  <div class="field">
    <%= f.label :song1 %>
    <%= f.select :song1_id,  options_for_select(Song.all.order(:name).map{|s|[s.name, s.id]},f.object.song1_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :song2 %>
    <%= f.select :song2_id, options_for_select(Song.all.order(:name).map{|s|[s.name, s.id]},f.object.song2_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :song3 %>
   <%= f.select :song3_id, options_for_select(Song.all.order(:name).map{|s|[s.name, s.id]},f.object.song3_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :song4 %>
    <%= f.select :song4_id, options_for_select(Song.all.order(:name).map{|s|[s.name, s.id]},f.object.song4_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :song5 %>
    <%= f.select :song5_id, options_for_select(Song.all.order(:name).map{|s|[s.name, s.id]},f.object.song5_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :song6 %>
    <%= f.select :song6_id, options_for_select(Song.all.order(:name).map{|s|[s.name, s.id]},f.object.song6_id), include_blank: true %>
  </div> 
  
  <div class="field">
    <%= f.label :song7 %>
    <%= f.select :song7_id, options_for_select(Song.all.order(:name).map{|s|[s.name, s.id]},f.object.song7_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :hymn1 %>
    <%= f.select :hymn1_id, options_for_select(Song.where("name LIKE ?",'[Гимн]%').order(:name).map{|s|[s.name, s.id]},f.object.hymn1_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :verse %>
    <%= f.select :verse_id, options_for_select(Slidever.all.order(date: :desc).map{|s|[s.date, s.id]},f.object.verse_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :hymn2 %>
    <%= f.select :hymn2_id, options_for_select(Song.where("name LIKE ?",'[Гимн]%').order(:name).map{|s|[s.name, s.id]},f.object.hymn2_id), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :hymn3 %>
    <%= f.select :hymn3_id, options_for_select(Song.where("name LIKE ?",'[Гимн]%').order(:name).map{|s|[s.name, s.id]},f.object.hymn3_id), include_blank: true %>
  </div>
  
  <div class="field">
    <%= f.label :hymn4 %>
    <%= f.select :hymn4_id, options_for_select(Song.where("name LIKE ?",'[Гимн]%').order(:name).map{|s|[s.name, s.id]},f.object.hymn4_id), include_blank: true %>
  </div>
  
  
  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/worship_slides/edit.html.erb
<h1>Editing Worship Slide</h1>

<%= render 'form', worship_slide: @worship_slide %>

<%= link_to 'Show', @worship_slide %> |
<%= link_to 'Back', worship_slides_path %>

app/views/worship_slides/index.html.erb
<% if not logged_in? %>  
<%= controller.redirect_to root_url %>
<% end %>

<p id="notice"><%= notice %></p>
<% provide(:title, 'Slides') %>
<h1>Worship Slides</h1>
<%= link_to 'New Worship Slide', new_worship_slide_path, class: "btn btn-primary" %>

 <%= will_paginate %>
    <ul class="worship_slide">
<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Song1</th>
      <th>Song2</th>
      <th>Song3</th>
      <th>Song4</th>
      <th>Song5</th>
      <th>Song6</th>
      <th>Song7</th>
      <th>Hymn1</th>
      <th>Verse</th>
      <th>Hymn2</th>
      <th>Hymn3</th>
      <th>Hymn4</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    
    <% @worship_slides.each do |worship_slide| %>
      <tr>
        <td><%= worship_slide.date %></td>
        <td><%= if worship_slide.song1 != nil then worship_slide.song1.name  else "" end %></td>
        <td><%= if worship_slide.song2 != nil then worship_slide.song2.name  else "" end %></td>
        <td><%= if worship_slide.song3 != nil then worship_slide.song3.name  else "" end %></td>
        <td><%= if worship_slide.song4 != nil then worship_slide.song4.name  else "" end %></td>
        <td><%= if worship_slide.song5 != nil then worship_slide.song5.name  else "" end %></td>
        <td><%= if worship_slide.song6 != nil then worship_slide.song6.name  else "" end %></td>
        <td><%= if worship_slide.song7 != nil then worship_slide.song7.name  else "" end %></td>
        <td><%= if worship_slide.hymn1 != nil then worship_slide.hymn1.name  else "" end %></td>
        <td><%= if worship_slide.verse != nil then worship_slide.verse.date  else "" end %></td>
        <td><%= if worship_slide.hymn2 != nil then worship_slide.hymn2.name  else "" end %></td>
        <td><%= if worship_slide.hymn3 != nil then worship_slide.hymn3.name  else "" end %></td>
        <td><%= if worship_slide.hymn4 != nil then worship_slide.hymn4.name  else "" end %></td>
        <td><%= link_to 'Show', worship_slide, class: "btn btn-info"  %></td>
        <td><%= link_to 'Edit', edit_worship_slide_path(worship_slide) , class: "btn btn-secondary" %></td>
        <td><%= link_to 'Destroy', worship_slide, method: :delete, data: { confirm: 'Are you sure?' } , class: "btn btn-danger" %></td>
      </tr>
    <% end %>
  </ul>
    
  </tbody>
  
</table>
<%= will_paginate %>
<br>

app/views/worship_slides/new.html.erb
<h1>New Worship Slide</h1>

<%= render 'form', worship_slide: @worship_slide %>

<%= link_to 'Back', worship_slides_path %>

app/views/worship_slides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @worship_slide.date %>
</p>

<p>
  <strong>Song1:</strong>
  <%= if @worship_slide.song1 != nil then @worship_slide.song1.name else "No song" end%>
</p>

<p>
  <strong>Song2:</strong>
  <%= if @worship_slide.song2 != nil then @worship_slide.song2.name else "No song" end%>
</p>

<p>
  <strong>Song3:</strong>
  <%= if @worship_slide.song3 != nil then @worship_slide.song3.name  else "No song" end %>
</p>

<p>
  <strong>Song4:</strong>
  <%= if @worship_slide.song4 != nil then @worship_slide.song4.name  else "No song" end %>
</p>

<p>
  <strong>Song5:</strong>
  <%= if @worship_slide.song5 != nil then @worship_slide.song5.name  else "No song" end %>
</p>

<p>
  <strong>Song6:</strong>
  <%= if @worship_slide.song6 != nil then @worship_slide.song6.name  else "No song" end %>
</p>

<p>
  <strong>Song7:</strong>
  <%= if @worship_slide.song7 != nil then @worship_slide.song7.name  else "No song" end %>
</p>

<p>
  <strong>Hymn1:</strong>
  <%= if @worship_slide.hymn1 != nil then @worship_slide.hymn1.name  else "No song" end %>
</p>

<p>
  <strong>Verse:</strong>
  <%= if @worship_slide.verse != nil then @worship_slide.verse.date else "No verses" end %>
</p>

<p>
  <strong>Hymn2:</strong>
  <%= if @worship_slide.hymn2 != nil then @worship_slide.hymn2.name  else "No song" end %>
</p>

<p>
  <strong>Hymn3:</strong>
  <%= if @worship_slide.hymn3 != nil then @worship_slide.hymn3.name  else "No song" end %>
</p>

<p>
  <strong>Hymn4:</strong>
  <%= if @worship_slide.hymn4 != nil then @worship_slide.hymn4.name  else "No song" end %>
</p>

<p>
  <strong>Data:</strong>
  <%= if @worship_slide.data != nil then "File created"  else "File need to create" end %>
</p>

<%= link_to 'Edit', edit_worship_slide_path(@worship_slide) , class: "btn btn-secondary" %> |
<%= link_to 'Back', worship_slides_path , class: "btn btn-info"  %> |
<%= link_to 'Download', worship_slide_op_download_path(:id => @worship_slide), target: '_self' , class: "btn btn-success" %> |
<%= link_to 'Delete_data', worship_slide_op_destroy_data_path(:id => @worship_slide) , class: "btn btn-danger" %> 