config/routes.rb
Rails.application.routes.draw do

  
  get 'worship_slide_op/create'
  
  get 'worship_slide_op/destroy_data'
  
  get 'worship_slide_op/download'
  
  
  
  resources :worship_slides
  resources :songs
  get 'download_song' => 'songs#download'
  get 'delete_song', to: 'songs#delete_data'
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  root 'pages#home'
  resources :filemakers
  resources :slidevers
 
  resources :users
  post '/signup',  to: 'users#create'
  get  '/signup',  to: 'users#new'
  
  get '/', to: 'pages#home'
  get  'help',    :to => 'pages#help'
  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'
  
  get "download_file", to: "slidevers#download_file"
  get 'delete_data', to: 'slidevers#delete_data'
  
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  

end

app/views/layouts/_footer.html.erb
<footer class="footer">

 
  <nav>
    <ul>
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">Rails News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Church app", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "SunWorPro", worship_slides_path %></li>
        <li><%= link_to "Verses", slidevers_path %></li>
        <li><%= link_to "Songs", songs_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user)  %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ANBC automation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
      <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
</head>
<body>
      <%= render 'layouts/header' %>

     <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
       <%= render 'layouts/footer' %>
        <%= debug(params) if Rails.env.development? %>
    </div>
    
    
</body>
</html>